sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  on_failure: change
node_js:
  - "5"
before_script:
  - npm prune
script: npm test && PUBLIC_PATH=/Drumkit API_GET_DRUMKIT=https://raw.githubusercontent.com/StudioLasso/Drumkit/master/drumkit.json npm run build
after_success:
  - npm run semantic-release
  - bash ./deploy-gh-pages.sh
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"