sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  on_failure: change
node_js:
  - "5"
before_script:
  - npm prune
script: PUBLIC_PATH=/react-drum-machine API_GET_DRUMKIT=https://raw.githubusercontent.com/StudioLasso/react-drum-machine/master/drumkit.json npm run build
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run semantic-release
  - bash ./deploy-gh-pages.sh
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
